### ISSUE TITLE
Release 1.1.2

### ISSUE THREAD

**Issue by tastypackets** [tastypackets/x12-parser#33]
Place holder issue to release update with TS and chunk ending in delimiter updates, since it's late and I might forget to return and do the release tomorrow. 😅 

Also it appears the package file wasn't being updated with the publishes, because npm is on 1.1.1 and package is set to 1.0.2

**Comment by ATLowther** [comment]
Hey,

Do you need help with this? What needs to be done before the latest changes are ready for `npm publish`?

**Comment by tastypackets** [comment]
I think we are all set, sorry I'm currently moving so it's been a bit busy. I'll get this published soon.

I should probably setup a release GitHub Action, so it's automated. 🙂

**Comment by tastypackets** [comment]
Published 👍
