### ISSUE TITLE
non beta release?

### ISSUE THREAD

**Issue by spearmootz** [tastypackets/x12-parser#9]
is 1.0.1 still considered beta?  is there a vague estimate as to when a non beta release might happen?

**Comment by tastypackets** [comment]
This has been in production use for a bit with no issues, so I think it is safe to take out of beta. I would still say the grouper needs to be updated / rewritten, the current grouper and schema was a first try and a lot has been learned from it.

1.0.1 was a bump in a dev dependency for a security issue. It looks like I'll need to release 1.0.2 for the lowdash.merg dev dependency.

I'll update the readme to reflect the extensive production use and indicate the main parser doesn't need to be marked as beta anymore.

**Comment by ceau** [comment]
It is a nice project, the code style is very clean.when v2 release?
I can create a pr if need

**Comment by tastypackets** [comment]
I don’t currently know when a v2 will be released, I’m working on a few other projects right now.

PRs / enhancements are always welcomed. I’d say one of the biggest things that needs to be done is locating and creating test for multiple other X12 files to ensure there are no missed edge cases. I built this to fulfill some needs in the medical industry, however I know this same format is used by many other industries that I do not have example files to use for testing.
